# Site settings
title: "Learning and privacy with incomplete data and weak supervision"
header-img: img/montreal.jpg
description: "Workshop Dec 12th @ NIPS'15"
baseurl: "/nips15workshop"
url: "http://giorgiopatrini.org"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

analytics :
  provider : google
  google :
      tracking_id : 'UA-67225517-1'
  getclicky :
  site_id :
