# Site settings
title: "Learning and privacy with incomplete data and weak supervision"
header-img: img/montreal.jpg
description: "Worskhop Dec 12 @ NISP'15"
baseurl: "/nips15workshop"
url: "http://giorgiopatrini.org"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
